import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://rlfzkvztmuwoziipagzz.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsZnprdnp0bXV3b3ppaXBhZ3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTE3MjksImV4cCI6MjA2MTI2NzcyOX0.TO3Ste14Ttubka4sYCU7ffvDCzohaRoqFG_9MnGzKRUeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsZnprdnp0bXV3b3ppaXBhZ3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTE3MjksImV4cCI6MjA2MTI2NzcyOX0.TO3Ste14Ttubka4sYCU7ffvDCzohaRoqFG_9MnGzKRU';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
